name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /opt/carcollection
          
          # Backup current state
          cp -r . ../carcollection-backup-$(date +%Y%m%d-%H%M%S)
          
          # Pull latest code
          git pull origin main
          
          # Backend setup
          cd backend
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pydantic-settings==2.1.0
          deactivate
          cd ..
          
          # Frontend setup
          cd car-collection-prototype
          npm install
          npm run build
          cd ..
          
          # Restart services
          sudo systemctl restart carcollection-backend
          sudo systemctl restart carcollection-frontend
          
          echo "Deployment completed successfully!"